name: Combine and Release Text Files

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build - Combine TXT Files
        run: cat *.txt > uBlockOrigin-FilterZ.txt
      - name: Set Release Name/Tag
        id: set_release_name
        run: echo "RELEASE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Test
        run: cat uBlockOrigin-FilterZ.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          name: "Release ${{ env.RELEASE_TAG }}"
          tag_name: ${{ env.RELEASE_TAG }}
          generate_release_notes: true
          files: uBlockOrigin-FilterZ.txt 
          draft: false
          prerelease: false
      - name: Release URL
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"